### PR TITLE
Use gmpy2

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@asmeurer, can you share the code in SymPy that fails with gmpy2?

**Comment by asmeurer** [comment]
I don't know what this was in reference to. As far as I know, SymPy should work with gmpy2, although it doesn't look like [we are testing it](https://travis-ci.org/sympy/sympy).

**Comment by isuruf** [comment]
SymPy crashed with an exception in gmpy2 while you were using it in SciPy 2016. Everything was fine when gmpy2 was removed.

**Comment by asmeurer** [comment]
I installed gmpy2 and the tests die in the middle of `test_pretty`:

```
$./bin/test pretty
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda3/bin/python  (3.5.2-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.7
random seed:        40864279
hash randomization: on (PYTHONHASHSEED=1369517888)

sympy/printing/pretty/tests/test_pretty.py[99] ......X.......................................................................................$
```

(the $ at the end is my prompt)

**Comment by asmeurer** [comment]
This must have been fixed upstream. I can't reproduce this any more, neither in sympy 1.1 or 1.0.

**Comment by asmeurer** [comment]
OK, I can reproduce it with gmpy2=2.0.7. But it's fixed with gmpy2=2.0.8.  I am unaware of any other issues with gmpy2, so any objections to this?

**Comment by asmeurer** [comment]
Maybe merge this branch with master first just to double check it all works with 1.1.

**Comment by isuruf** [comment]
@richardotis, thoughts?

**Comment by richardotis** [comment]
I'm not sure how fancy the conda dependency graph can get, but ideally we would blacklist the gmpy2 versions that will crash sympy. Something like (pseudocode):
```
- gmpy2>=2.0.8 or "not installed" [not win]
- gmpy2>=2.1.0 or "not installed" [win]
```
Alternatively, as a workaround, sympy itself can do version detection and treat incompatible versions as uninstalled.

**Comment by asmeurer** [comment]
There was some talk of optional dependencies for conda. I don't know if it was competed.

**Comment by asmeurer** [comment]
I guess it is this https://github.com/conda/conda/issues/1696#issuecomment-300309736, which will be in the next version of conda. 

But honestly I think until that we should just depend on gmoy2. Conda makes it easy to install and SymPy runs better when it is.

**Comment by richardotis** [comment]
In that case, I'm +1 to merge this.

**Comment by asmeurer** [comment]
Should we add version restrictions?

**Comment by richardotis** [comment]
I think so. If we think it's easy to install, it should also be easy to update.

**Comment by isuruf** [comment]
This is ready for review now

**Pull request merged**
