### PR TITLE
Update recipe to 1.1

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by scopatz** [comment]
Have you pushed up to pypi yet? It doesn't seem to be able to find the URL.

**Comment by asmeurer** [comment]
Don't know where that URL was coming from. Seems to be using a mix of old and new style. Fixed it to just use pypi.io.

**Comment by scopatz** [comment]
Looks like some windows builds have started to fail. Has this been rerendered recently?

**Comment by asmeurer** [comment]
Did a rerender.

**Comment by scopatz** [comment]
Congrats!

**Pull request merged**
