### PR TITLE
MNT: rerender

### LINKED ISSUE #26: @conda-forge-admin, rerender
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #26.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #26

### CODE REVIEW

**Comment by isuruf** [comment]
@scopatz, forgot to do a rerender.

**Comment by scopatz** [comment]
Thanks!

**Comment by asmeurer** [comment]
This fixes this issue https://github.com/conda-forge/sympy-feedstock/pull/25#pullrequestreview-375213949?

**Comment by isuruf** [comment]
Yes

**Pull request merged**
